### ISSUE TITLE
[Feature Request] suggests adding calendar components


### ISSUE THREAD

**Issue by lenxeon** [iview/iview#2508] opened 2017-11-28 06:15 UTC
### What problem does this feature solve?
有一些场景里并不是只使用日期选择，calendar在产品里能更好的展现一些日程行动。

### What does the proposed API look like?
基本功能即可

**Comment by SergioCrisostomo** [comment] 2018-02-28 10:03
Closing as duplicate of https://github.com/iview/iview/issues/1910

**Closed by SergioCrisostomo** 2018-02-28 10:03 UTC
