### ISSUE TITLE
[建议]按Tab键的时候可以让Select能获取focus

### ISSUE THREAD

**Issue by fonhen** [iview/iview#764] opened 2017-04-24 04:05 UTC
[建议]按Tab键的时候可以让Select能获取focus

**Comment by thearabbit** [comment] 2017-05-03 12:38
+1

**Comment by ozeebee** [comment] 2017-06-26 12:56
+1

**Comment by javady** [comment] 2017-09-12 03:50
2.3也不支持

**Comment by SergioCrisostomo** [comment] 2017-11-18 10:18
duplicate of https://github.com/iview/iview/issues/1647

**Closed by SergioCrisostomo** 2017-11-18 10:18 UTC
Labels: need to optimize, Select

**Comment by var-zhangbao** [comment] 2018-03-28 06:29
+1

**Comment by leixu2txtek** [comment] 2018-05-08 02:36
+1
