### ISSUE TITLE
[Feature Request] adds Calendar components


### ISSUE THREAD

**Issue by weihongyu12** [iview/iview#3071] opened 2018-02-28 02:47 UTC
### What problem does this feature solve?
按照日历形式展示数据的容器，可以展示日程表

### What does the proposed API look like?
参见[Ant Design Calendar](https://ant.design/components/calendar-cn/)

**Comment by SergioCrisostomo** [comment] 2018-02-28 10:03
Closing as duplicate of https://github.com/iview/iview/issues/1910

**Closed by SergioCrisostomo** 2018-02-28 10:03 UTC
