### ISSUE TITLE
IVIEW Date Piker 

### ISSUE THREAD

**Issue by murilolivorato** [iview/iview#6315] opened 2019-09-28 02:13 UTC
Hello , I have this date piker -
```
{{ post_date }} 

 <DatePicker size="large"   type="date"  format="dd/MM/yyyy"  v-model="form.post_date" placeholder="Selecione uma Data"></DatePicker>
```

when I select it shows this -

```
Sat Sep 21 2019 00:00:00 GMT-0300 (Brasilia Standard Time)

```

how could I just show this instead - 

```
2019-09-21

```
?

**Comment by DebugIsFalse** [comment] 2019-10-09 02:07
You can create new variable to set the value
for example 
data(){
      return {
          post_date : ''
     }
},
methods : {
    onChange(val){
        this.post_date = new Date(val);
   }
}

**Comment by DebugIsFalse** [comment] 2019-10-29 03:59
Duplicate of #5940 #6296

**Closed as completed** 2019-10-29 04:00 UTC
