### ISSUE TITLE
Tree属性BUG

### ISSUE THREAD

**Issue by panxch** [iview/iview#2162] opened 2017-10-23 01:34 UTC
Tree：如果使用watch给data赋值，发现tree控件节点点击事件错误

**Comment by SergioCrisostomo** [comment] 2017-10-23 05:51
@panxch can you create a example of the problem?

使用下面的在线链接可以快速创建示例
https://jsfiddle.net/yyrzhm46/

**Comment by SergioCrisostomo** [comment] 2017-10-26 11:51
@panxch today we released `2.6.0`. Please test this problem in this new version and comment here if the problem is still there.

**Comment by SergioCrisostomo** [comment] 2017-11-01 09:51
@panxch I think this was fixed in `2.6.0`. Please comment if the problem is still there. Closing for now.

**Closed by SergioCrisostomo** 2017-11-01 09:51 UTC
Labels: provide example
