### ISSUE TITLE
[Bug Report]Selected not shown 

### ISSUE THREAD

**Issue by suconghou** [iview/iview#3831] opened 2018-06-05 10:02 UTC
### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

### Reproduction link
[https://jsfiddle.net/suconghou/mkp4Lq3t/](https://jsfiddle.net/suconghou/mkp4Lq3t/)

### Steps to reproduce
load page

### What is expected?
some selected value should shown

### What is actually happening?
selected value shown whenever how options or values changes

**Comment by Xotic750** [comment] 2018-06-05 14:54
I tried your link and it worked for me.
![screenshot from 2018-06-05 16-53-53](https://user-images.githubusercontent.com/216041/40984001-24d55a90-68e1-11e8-84b9-a6a9d1ab89d8.png)

**Comment by David-Tsui** [comment] 2018-06-06 00:50
Not a bug.
Please take a look at **async part** of JavaScript.

https://jsfiddle.net/9dcxq51o/

**Comment by suconghou** [comment] 2018-06-06 02:13
@David-Tsui  Not a bug ? excuse me , This is just a simple demo . In real world , options and model changes many times and varied. I know promise and async .  **But You can not ask user set options value before model value In any scene,  and once model value set , cannot change options value** 

I have never seen such a crappy implementation!

**Comment by David-Tsui** [comment] 2018-06-06 07:28
@suconghou OK, it works before iview 2.14, maybe I misunderstand what you mean.

**Comment by Xotic750** [comment] 2018-06-06 10:34
@suconghou Instead of getting upset and belittling the work, how about trying to give us some more information about the problem: a fuller description of the problem and expectation, some exact steps to reproducing the issue, even video of what is or is not happening. This is an open project that welcomes the input, feedback, and the efforts that people put into making things work; sometimes things don't work. 

It looks like you are expecting `Sydney` to be selected once the `Select` is populated with data, but you select `Sydney` 100ms before you populate `Select` with any data. If I set the `getValue` delay to say 100ms, after `getData`, then `Sydney` is selected.

**Comment by suconghou** [comment] 2018-06-06 11:19
the bug is very clear. the selected one should be shown whenever options data or model data has changed.

by the way , it works well a few months ago .

https://jsfiddle.net/suconghou/mhLkuocb/2/

**Comment by Xotic750** [comment] 2018-06-06 17:33
Ok, that gives a helpful comparison. I'm not sure what the deigned expectation is in this case, but the old method and the new clearly work differently.

**Comment by Xotic750** [comment] 2018-06-07 08:09
I have just tested the 2.0 repo, which has some further fixes in it after the 2.14.1 release, and this appears to exhibit the original behaviour.

https://jsfiddle.net/mkp4Lq3t/27/

**Comment by SergioCrisostomo** [comment] 2018-06-07 08:13
@suconghou hi!
I did a big refactor in the Select component because it had limitations and performance issues. I read your comment _"I have never seen such a crappy implementation!"_. If you have a better solution I am happy to review your Pull Request. It took me many many hours to refactor and include all the functionality Select has. If you can do it better I am happy to see some code and learn.

Meanwhile I'm happy to review and fix bugs you might find and together find the way forward to improve iview.

**Comment by icarusion** [comment] 2018-06-07 08:18
This issue has been fixed in pr #3798 , wait for next iView version

**Closed by icarusion** 2018-06-07 08:18 UTC

**Comment by suconghou** [comment] 2018-06-07 08:43
@SergioCrisostomo  Thank you for your works , I know it is difficult to make all the features work well given that more and more code and  functions was added. I am also glad to share my suggestions and problems in my daily work to make iview better.

**Comment by m430** [comment] 2018-06-07 15:12
@suconghou I has been fixed this issue in PR #3798 , please wait the next version. it's going to be more stable.

**Comment by suconghou** [comment] 2018-06-07 15:19
@m430  It's ok , Thank you.
