### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by LesterSixNet** [iview/iview#6143] opened 2019-08-01 10:01 UTC
Carousel
children add  click or other event,
and loop

then loop once click don't trigger

**Comment by DebugIsFalse** [comment] 2019-08-28 06:26
please use 'https://run.iviewui.com' to provide the example

**Comment by DebugIsFalse** [comment] 2019-09-03 03:22
> please use 'https://run.iviewui.com' to provide the example



> Carousel
> children add click or other event,
> and loop
> 
> then loop once click don't trigger

Duplicate of #6230

**Closed as completed** 2019-09-19 06:28 UTC
Labels: bug, duplicate
