### ISSUE TITLE
When the [Bug Report]Select selector selects two attributes of clearable filterable at the same time, if the code is formatted, there will be a style problem.


### ISSUE THREAD

**Issue by zlu1123** [iview/iview#3593] opened 2018-05-10 02:55 UTC
### Environment
window10 64位   谷歌浏览器63.0.3239.132（正式版本）  iview基于最新版本

### Reproduction link
[https://jsfiddle.net/LukeZhang/jcamocus/1/](https://jsfiddle.net/LukeZhang/jcamocus/1/)

### Steps to reproduce
1.点击select标签，
2.选择下拉框中选择任意一条数数据

### What is expected?
选择的数据左对齐填充select框

### What is actually happening?
选择的数据未能左对齐填充select框

---
事后经过测试，发现·{{}}·因为代码格式化后左侧有空格，就会影响左对齐，但是上述两个属性，任意单写，都可以格式化代码

**Comment by Miller547719886** [comment] 2018-05-10 03:50
```
<Option
                    :label="optionAll.label"
                    :value="optionAll.key">
                    <!-- {{ optionAll.label }} -->
                  </Option>
```
use prop label instead of "{{}}" can solve this problem

**Comment by zlu1123** [comment] 2018-05-10 08:02
@Miller547719886 我已经解决了当前的问题，提issue是想让iview看一下这个组件内部的问题，便于他们修改。谢谢您的方案，后续会采用您说的

**Comment by SergioCrisostomo** [comment] 2018-05-11 07:38
duplicate of https://github.com/iview/iview/issues/3405

**Comment by SergioCrisostomo** [comment] 2018-05-11 09:08
Fixed in https://github.com/iview/iview/pull/3579

**Closed by SergioCrisostomo** 2018-05-11 09:08 UTC
