### ISSUE TITLE
导出表格中文为乱码，在Chrome浏览器上

### ISSUE THREAD

**Issue by sosxyf** [iview/iview#2138] opened 2017-10-19 08:48 UTC

**Comment by SergioCrisostomo** [comment] 2017-10-19 09:18
@sosxyf can you provide a example of your problem?

 使用下面的在线链接可以快速创建示例 
 https://jsfiddle.net/yyrzhm46/

**Comment by SergioCrisostomo** [comment] 2017-11-01 09:52
I cannot reproduce this. Closing. Please provide example if the problem is still there.

**Closed by SergioCrisostomo** 2017-11-01 09:52 UTC
Labels: provide example
