### ISSUE TITLE
[Bug Report] Cascader load-data adds an exception to the default value when the change-on-select attribute is added


### ISSUE THREAD

**Issue by sakura-flutter** [iview/iview#5376] opened 2019-03-06 07:53 UTC
### Environment
windows10/chrome 71.0.3578.98 /vue 2.5.22

### Reproduction link
[https://run.iviewui.com/RaUQyurq](https://run.iviewui.com/RaUQyurq)

### Steps to reproduce
链接所示，联动没有显示出'夫子庙'，且数据被改动成['jiangsu', 'nanjing']，缺少默认值的最后一项
当去除change-on-selec属性t时，正常

### What is expected?
按实际默认值显示，添加change-on-selec属性时点选每级菜单选项值都会发生变化

### What is actually happening?
添加change-on-selec属性时默认值缺少最后一项

**Comment by DebugIsFalse** [comment] 2019-12-05 09:40
Duplicate of #6158

**Closed as completed by DebugIsFalse** 2019-12-05 09:40 UTC
